### ISSUE TITLE
AttributeError: 'str' object has no attribute 'resolve' error on first attempt

### ISSUE THREAD

**Issue by BjornW** [hay/audio2text#1]
After installing and trying to run it for the first time I get the error below: 

``Traceback (most recent call last):
  File "audio2text/./audio2text.py", line 50, in <module>
    whisper.transcribe(in_path, out_path)
  File "audio2text/audio2text/whisper.py", line 55, in transcribe
    self.transcribe_processed_wav(tmp_file, out_path)
  File "audio2text/audio2text/whisper.py", line 61, in transcribe_processed_wav
    str(self.whisper_path.resolve()),
AttributeError: 'str' object has no attribute 'resolve'``

The command I've used was: 
``./audio2text.py -w ../whisper.cpp/main -m ../whisper.cpp/models/ggml-tiny.bin -i test/berliner.og
g -o test/berliner.csv -of csv``

Am I overlooking something?

Using verbose as results in: 

``Initialized AudioToText
Transcribing test/berliner.ogg as test/berliner.csv
Converting test/berliner.ogg to tmp/jX85WfkYSMTfiqru4UTWEn.wav
Traceback (most recent call last):
  File "audio2text/./audio2text.py", line 50, in <module>
    whisper.transcribe(in_path, out_path)
  File "audio2text/audio2text/whisper.py", line 55, in transcribe
    self.transcribe_processed_wav(tmp_file, out_path)
  File "audio2text/audio2text/whisper.py", line 61, in transcribe_processed_wav
    str(self.whisper_path.resolve()),
AttributeError: 'str' object has no attribute 'resolve'``

Using Python 3.10.6 on Ubuntu Linux 22.04.1

**Comment by hay** [comment]
The whisper and model path weren't instances of the `Path` class from `pathlib`. This has been fixed now.

**Comment by BjornW** [comment]
I can confirm that it works now 🥳!

**Comment by hay** [comment]
Cool!
